name: Issue Rename
"on":
  issues:
    types:
      - opened
jobs:
  issuesOpened:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: nanashili/CodeEdit-Github-Action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
